# permissions for end users to edit taloscontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: taloscontrolplane-editor-role
rules:
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - taloscontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - taloscontrolplanes/status
  verbs:
  - get
