apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: taloscontrolplane-sample
spec:
  controlPlaneSpec:
    init:
      generateType: init
    controlplane:
      generateType: controlplane